[package]
name = "reth-codecs"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
default = ["compact"]
compact = ["codecs-derive/compact"]
scale = ["codecs-derive/scale"]
postcard = ["codecs-derive/postcard"]
no_codec = ["codecs-derive/no_codec"]
arbitrary = ["revm-primitives/arbitrary", "dep:arbitrary", "dep:proptest", "dep:proptest-derive"]

[dependencies]
bytes = "1.4"
codecs-derive = { version = "0.1.0", path = "./derive", default-features = false }
revm-primitives = { workspace = true, features = ["serde"] }

# arbitrary utils
arbitrary = { version = "1.1.7", features = ["derive"], optional = true }
proptest = { version = "1.0", optional = true }
proptest-derive = { version = "0.3", optional = true }

[dev-dependencies]
revm-primitives = { workspace = true, features = ["serde", "arbitrary"] }

serde = "1.0"
modular-bitfield = "0.11.2"
test-fuzz = "3.0.4"

arbitrary = { version = "1.1.7", features = ["derive"] }
proptest = { version = "1.0" }
proptest-derive = "0.3"
